### ISSUE TITLE
New element moved to the end of the list

### ISSUE THREAD

**Issue by SeriousM** [webtempest/meteor-animate#3]
It seems that your code is rearranging/moving any new element in a list to the end even the subscription is sorting it the other way around.

Subscription:

``` js
//...
return {posts: Posts.find({},{sort:{timestamp: -1}})}
//...
```

Consumer:

``` html
    {{#transition in="flipInX" out="flipOutX"}}
      {{#each posts}}
          <div>
        {{message}}
          </div>
      {{/each}}
    {{/transition}}
```

Everything is fine again once I remove the transition.

Thanks for your really cool package!

**Comment by mplatts** [comment]
Thanks will have a look

**Comment by mplatts** [comment]
@SeriousM can you update and try again - just pushed a potential fix

**Comment by SeriousM** [comment]
yep, I can confirm that 2945e4a559081f04d5217ce21064524cd48ab073 fixed the problem.
thank you very much!
