### ISSUE TITLE
Package without bundled animate.css

### ISSUE THREAD

**Issue by derwaldgeist** [webtempest/meteor-animate#6]
I like this package, but I already included animate.css in my application using the SASS version - which gives better control about which animations are actually included, and thus allows me to reduce the file sizes for my mobile app. So I would like to recommend to split this package in two: one for the Meteor side of the implementation, and one for the base animate.css file.

**Comment by mplatts** [comment]
True that is one thing I don't like about this. I'm getting more into react at the moment so not sure when I'll have time to work more on this. For now maybe just clone into your packages folder and then remove the animate.css file and remove the reference to it in `package.js`.
