### ISSUE TITLE
Triggering static animations

### ISSUE THREAD

**Issue by linker-err0r** [webtempest/meteor-animate#7]
In the example, and documentation, static animations only 'animate' when they're first rendered. Is there a way to trigger an animation in response to an event? Say, for example, if I want to apply an in-place shake to incorrectly filled out form fields and when the user clicks the button, the invalid fields animate. Is there a way to do this? Or should I just 'blink' something else to trigger it?

**Comment by Falieson** [comment]
Lil disclaimer: I haven't used the animate package yet, and am still learning more about meteor every day. I think that you could use template.name.events `'click #button': func(){ //do something from https://github.com/daneden/animate.css }`

**Comment by mplatts** [comment]
@deathgaze yes I'd do as @Falieson suggests. My code shows how I do it:

``` coffee
$node.addClass("animated #{animation}")
```

Where `animation` is the name of the animation ("bounce", "flash" etc). Once the animation is complete you can remove that class and do it again later (use $.delay or listen for the end of transition event). Hope that makes sense
